## => Site Settings
##############################
text_skin: dark
highlight_theme: tomorrow-night
url     : https://slugsec.ucsc.edu
title   : Slug Security
description: The student-run cybersecurity club at UC Santa Cruz.

## => Language and Timezone
##############################
lang: en
timezone: America/Los_Angeles

## => Author and Social
##############################
author:
  type      : organization
  email     : slugsec@ucsc.edu
  linkedin  : SlugSec
  github    : SlugSecurity
  discord   : NUVZCumQXB
  twitter   : SlugSec
  mastodon  : #infosec.exchange/@SlugSec
  instagram : SlugSec
  youtube   : # button code is there, but need svg in the assets folder
  ctftime   : '228068'

## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : /posts # "/archive.html" (default)

## => Markdown Enhancements
##############################
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

mermaid: # false (default), true

chart: # false (default), true

## => Paginate
##############################
paginate: 3
paginate_path: /page:num # don't change this unless for special need

## => Sharing
##############################
sharing:
  provider: false # false (default), "addtoany", "addthis", "custom"

  ## AddThis
  addthis:
    id: # AddThis pubid, e.g. ra-5xxxxxxxxxxx

## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "valine", "custom"

  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id

## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class

## => Search
##############################
search:
  provider: default # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID

## => Analytics
##############################
analytics:
  provider: google

  google:
    tracking_id : G-YFR850WSX3
    anonymize_ip: false

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : /:year/:month/:title

#exclude:
source: src/

collections:
  writeups:
    output: true
    permalink: /:year/:month/:title-Writeup

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: false
      pageview: true
  - scope:
      path: ""
      type: writeups
    values:
      layout: article
      aside:
        toc: true
      values:
        nav_key: writeups
      pageview: true

## => Plugins
##############################
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
