site_name: Slug Security
site_url: https://slugsec.ucsc.edu
site_author: Slug Security
site_description: 'The student-run cybersecurity club at UC Santa Cruz.'

docs_dir: src

nav:
  - Posts:
      - posts/index.md
  - Writeups: 
      - writeups/index.md
  - Events: events.md
  - Home: index.md
  - Highlights: highlights.md
  - About:
    - FAQs: about/faqs.md
    - Officers: about/officers.md
    - Sponsors: about/sponsors.md
  - Join: join.md

not_in_nav: |
  /_assets/*
  /_includes/*
  /_data/*

theme: 
  name: material
  custom_dir: src/_assets/overrides
  font:
    text: HelveticaNeue-Medium
    code: JetBrainsMono-Nerd
  favicon: _assets/favicon.ico
  logo: _assets/logo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.prune
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - toc.follow
    - announce.dismiss
  palette:
    - scheme: slate
      primary: deep orange
      accent: deep orange

plugins:
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - events.md
  - blog:
      blog_dir: posts
      post_dir: '{blog}/data'
      blog_toc: true
      pagination_if_single_page: true
      pagination_per_page: 5
      post_excerpt_max_authors: 2
      post_url_format: '{slug}'
      authors_file: _data/authors.yml
  - blog:
      blog_dir: writeups
      post_dir: '{blog}/data'
      blog_toc: true
      pagination_if_single_page: true
      pagination_per_page: 5
      post_excerpt_max_authors: 2
      authors_profiles: true
      post_url_format: '{slug}'
      authors_file: _data/authors.yml
  - meta
  - optimize:
      enabled: false #!ENV [CI, false]
  - typeset
  - kroki
  - inline-svg:
      alt_name: Kroki
  - social:
      enabled: !ENV [CI, false]
      cards_layout_dir: src/_assets/layouts
      cards_layout: custom
  - minify:
      minify_html: true
  - open-in-new-tab
  - privacy:
      enabled: !ENV [CI, false]
      assets_exclude:
        - unpkg.com/*
        - fonts.googleapis.com/*
        - giscus.app/*
  - mkdocs-add-teaser:
        teaser_class: 'teaser'
        add_to_meta: true
  - plotly
  - rss:
      match_path: "posts/data/.*|writeups/data/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - glightbox:
      draggable: false
      auto_caption: true
      caption_position: bottom
  - redirects:
      redirect_maps:
        'discord.md': 'https://discord.gg/NUVZCumQXB'
        'register.md': 'https://forms.gle/Ae97RjFZ8M2JJgF87'
        'interest.md': 'https://forms.gle/7qS1jBXrgfiajckp7'
        '2021/11/CyberForce.md': 'posts/data/2021/cyberforce/index.md'
        'posts/CyberForce-2021.md': 'posts/data/2021/cyberforce/index.md'
        '2021/12/Codebreaker.md': 'posts/data/2021/codebreaker/index.md'
        'posts/Codebreaker-2021.md': 'posts/data/2021/codebreaker/index.md'
        '2022/11/CyberForce.md': 'posts/data/2022/cyberforce/index.md'
        'posts/CyberForce-2022.md': 'posts/data/2022/cyberforce/index.md'
        '2022/12/Codebreaker.md': 'posts/data/2022/codebreaker/index.md'
        'posts/Codebreaker-2022.md': 'posts/data/2022/codebreaker/index.md'
        '2023/04/eCTF.md': 'posts/data/2023/eCTF/index.md'
        'posts/eCTF-2023.md': 'posts/data/2023/eCTF/index.md'
        'posts/Laundry-2024.md': 'posts/data/2024/laundry/index.md'
  - macros:
      include_yaml:
          - src/_data/sponsors.yml
          - src/_data/highlights.yml
          - src/_data/officers.yml

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - src/_includes/abbreviations.md

extra:
  analytics: 
    provider: google
    property: G-YFR850WSX3
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/NUVZCumQXB
      name: Join our Discord
    - icon: fontawesome/regular/envelope
      link: 'mailto:slugsec@ucsc.edu'
      name: Send us an email
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/SlugSec
      name: Follow us on Twitter
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/SlugSec
      name: Follow us on Instagram
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@SlugSec
      name: Subscribe to our YouTube
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/SlugSec
      name: Connect with us on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/SlugSecurity
      name: Follow us on GitHub
    - icon: fontawesome/solid/flag
      link: https://ctftime.org/team/228068
      name: Join us on CTFtime
  msg: 'Slug Security is a 501(c)(3) nonprofit organization (EIN 94-1539563).'
copyright: '&copy; 2024 Regents of the University of California'

extra_css:
  - _assets/css/extra-fonts.css
  - _assets/css/custom-header.css
  - _assets/css/custom-footer.css
  - _assets/css/blog-listing.css
  - _assets/css/extras.css
  - _assets/css/sponsors.css
  - _assets/css/highlights.css
  - _assets/css/officers.css
  - _assets/css/home.css

hooks:
  - src/_assets/hooks/images.py
  - src/_assets/hooks/blog_context.py
