name: Build MkDocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          sparse-checkout: |
            src
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: sudo apt install pngquant
      - run: pip install lxml
      - run: pip install git+https://${GH_TOKEN}@github.com/0xfbad/framework.git
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force || true
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}