name: Pull latest writeups and rebuild site

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main site repo
      uses: actions/checkout@v3

    - name: Update writeups submodule
      run: |
        git submodule update --init --recursive
        cd writeups
        git pull origin main

